### ISSUE TITLE
failure to include a file does not fail the build

### ISSUE THREAD

**Issue by travi** [pact-foundation/grunt-pact#3]
as seen in [this build](https://circleci.com/gh/travi/travi.org-admin/1571) grunt-pact exits as successful when it fails to load a file. My assumption was that this would fail the build.

**Comment by mboudreau** [comment]
Yeah, maybe it should make it fail unless force is specified. I'll change
this tonight.

**Comment by mboudreau** [comment]
@travi This has been fixed in the newly released version 3.2.0.  Cheers.

**Comment by travi** [comment]
thanks!
