### ISSUE TITLE
shasum check failure for pact-provider-verifier

### ISSUE THREAD

**Issue by travi** [pact-foundation/grunt-pact#5]
when trying to install the latest version, I've been seeing the following error:

```
npm WARN shasum check failed for /var/folders/9l/q9klhdys15xcxrqxpmh76ccr0000gn/T/npm-41060-2da3829b/registry.npmjs.org/_40pact-foundation/pact-provider-verifier/-/pact-provider-verifier-0.1.0.tgz
npm WARN Expected: 9e827fa0aa8242c7996508e842895b23ecaacf0d
npm WARN Actual:   6c879bec021da0082bbfbf724f5a4ab3ff50a4f9
npm WARN From:     https://registry.npmjs.org/@pact-foundation/pact-provider-verifier/-/pact-provider-verifier-0.1.0.tgz
```

i was seeing this error a few months ago, but haven't had a chance to work with it for a while. i haven't been having any other npm issues, but am seeing the issue again now that i've attempted to install again. 

i'm working on osx and currently using node v6.6.0

**Comment by travi** [comment]
i was hopeful that [updating `pact-node`](https://github.com/travi/grunt-pact/tree/pact-node) would be enough to solve this, but it gives me the same issue, even though it does pull in a more recent version of `pact-provider-verifier`:

```
npm ERR! shasum check failed for /var/folders/9l/q9klhdys15xcxrqxpmh76ccr0000gn/T/npm-42238-e3525f37/registry.npmjs.org/_40pact-foundation/pact-mock-service/-/pact-mock-service-0.9.0.tgz
npm ERR! Expected: 5c5eefa72a4a2d86a198e6c450fac514f9826cdf
npm ERR! Actual:   51f830c0cbecadbb9b8ad8ab3eafb2a48cba1cab
npm ERR! From:     https://registry.npmjs.org/@pact-foundation/pact-mock-service/-/pact-mock-service-0.9.0.tgz
```

**Comment by mboudreau** [comment]
Try doing an `npm cache clear` and try again

**Comment by travi** [comment]
i should have mentioned that i had already done that for npm, but your nudge got me to dig deep enough to get nvm's cache cleared as well. i still don't have my head around the difference, but that seems to have taken care of it. 

it seems that i have this problem fairly regularly with this chain of packages, but no others. i don't have an explanation, but i'll have to remember to go deep when clearing related packages.

sorry for the noise.

**Comment by mboudreau** [comment]
It's probably because this is a binary and not source code, hence the final
size is quite large.  I have seen this issue before when the internet
connection isn't great.  Best way to fix it is to move away from the very
large Ruby binary being created, which we've already done some good strides
with the pact-reference repo.  We simply haven't integrated it just yet
with pact-node and grunt-pact.

**Comment by travi** [comment]
thanks for the info. that does make a lot of sense, especially since my connection at home is, in fact, horrible. great to hear progress continues in the direction of even better node support. really appreciate the work you all are doing.
